epochs: 500
batch_size: 32
test_batch_size: 1
check_epoch: 9
lr_decay: 0.5 # Scheduler parameter, learning rate decay factor
step_size: 50 # Scheduler parameter, change learning rate after {step_size} epochs
FC: True
data_names: 