train: /home/singh_a_WMGDS.WMG.WARWICK.AC.UK/wmg/polymer_sort/datasets/Jeon/group2/preprocessed/train/
val: /home/singh_a_WMGDS.WMG.WARWICK.AC.UK/wmg/polymer_sort/datasets/Jeon/group2/preprocessed/val/
test: /home/singh_a_WMGDS.WMG.WARWICK.AC.UK/wmg/polymer_sort/datasets/Jeon/group2/preprocessed/test/

class_names: 
  - PE
  - PET
  - PP
  - PS

model_name: Transformer
model_arguments:
  num_transformer_layers: 3
  input_size:  400
  num_classes:  4
  mlp_size:  64
  patch_size:  5
  embedding_dim:  20
  num_heads:  4
  pre_module: True


loss_name: cross_entropy
loss_arguments:

optimizer_name: 'adam'
optimizer_arguments:
  lr:  0.01
  # betas:  [0.9, 0.999]
  # eps:  1e-8
  # weight_decay: 0.0
