train: /home/singh_a_WMGDS.WMG.WARWICK.AC.UK/wmg/polymer_sort/datasets/Leone/all_labeled/5class/withOthers/train/
val: /home/singh_a_WMGDS.WMG.WARWICK.AC.UK/wmg/polymer_sort/datasets/Leone/all_labeled/5class/withOthers/val/
test: /home/singh_a_WMGDS.WMG.WARWICK.AC.UK/wmg/polymer_sort/datasets/Leone/all_labeled/5class/withOthers/test/
class_names: 
  - PE
  - PET
  - PP
  - PS
  - others


model_name: ANN
model_arguments:
  input_size: 4000
  num_classes:  5
  pre_module: True


loss_name: weighted_ce
loss_arguments:

optimizer_name: 'adam'
optimizer_arguments:
  lr:  0.01
  # betas:  [0.9, 0.999]
  # eps:  1e-8
  # weight_decay: 0.0
