train: /home/singh_a_WMGDS.WMG.WARWICK.AC.UK/wmg/polymer_sort/datasets/Jeon/group1/preprocessed/train/
val: /home/singh_a_WMGDS.WMG.WARWICK.AC.UK/wmg/polymer_sort/datasets/Jeon/group1/preprocessed/val/
test: /home/singh_a_WMGDS.WMG.WARWICK.AC.UK/wmg/polymer_sort/datasets/Jeon/group1/preprocessed/test/

class_names: 
  - PE
  - PET
  - PP
  - PS
  - PVC

model_name: CNN
model_arguments:
  num_classes:  5
  input_size: 4000
  
loss_name: cross_entropy
loss_arguments:

optimizer_name: 'adam'
optimizer_arguments:
  lr:  0.01
  # betas:  [0.9, 0.999]
  # eps:  1e-8
  # weight_decay: 0.0
