train: /home/singh_a_WMGDS.WMG.WARWICK.AC.UK/wmg/polymer_sort/datasets/Edi_MIR/baseline/2/train/
val: /home/singh_a_WMGDS.WMG.WARWICK.AC.UK/wmg/polymer_sort/datasets/Edi_MIR/baseline/2/val/
test: /home/singh_a_WMGDS.WMG.WARWICK.AC.UK/wmg/polymer_sort/datasets/Edi_MIR/baseline/2/test/

class_names: 
  - PE
  - PP
  - PET
  - PS
  - PVC
  - PMMA
  - ABS
  - PC
  - Others

model_name: CNN Inception
model_arguments:
  num_classes:  9
  pre_module: False
  input_size:  4000

loss_name: cross_entropy
loss_arguments:

optimizer_name: 'adam'
optimizer_arguments:
  lr:  0.01
  # betas:  [0.9, 0.999]
  # eps:  1e-8
  # weight_decay: 0.0
